### ISSUE TITLE
Add special method to get all current Announcements

### ISSUE THREAD

**Issue by arthurrump** [arthurrump/Zermelo.API#1]
There's an (undocumented) option available in the Zermelo REST API to get only the 'current' Announcements. I discovered this feature in the [official Zermelo App AjaxManager.js file](https://github.com/zermelo-software/zermelo-app/blob/4e9e446541343037ca78e20c29d4fe2d2830da37/www/app/AjaxManager.js) (line 103). This would be a good addition to the `AnnouncementsEndpoint` as `GetCurrentAsync()`.

**Comment by arthurrump** [comment]
@gkrol-zermelo Shouldn't this feature be documented [here](https://zermelo.atlassian.net/wiki/display/DEV/Announcement)?

**Comment by gkrol-zermelo** [comment]
Yes, the "current" parameter is what you should use if you want to show announcements to users. I've added it to the documentation.
